### ISSUE TITLE
As a developer, I would like to deploy finesse-frontend

### ISSUE THREAD

**Issue by ThomasCardin** [ai-cfia/infra#16]
- [ ] Step 1: Deploy finesse front-end on kubernetes
- [ ] Step 2: Connect the backend with the frontend
- [ ] Step 3: Test

**Comment by rngadam** [comment]
@ThomasCardin you want to revisit the checklist with open tasks and close them when closing issues to ensure that nothing has been forgotten (and postpone work to new issues if so)
